"""
============================================================================
PRISM: Document Chunks Importer
============================================================================
Loads a pre-generated document_chunks export into a freshly-seeded Prism
database. The export contains the chunk text, the pre-computed vector
embeddings, and natural keys that identify which source row each chunk
belongs to. This script looks up the new source_id values in the target
database (which were generated by prism-seed.py) and INSERTs the chunks
into DOCUMENT_CHUNKS with the correct foreign-key relationships.

Input formats (auto-detected by file extension):
    data/document_chunks.json.gz  - compressed JSON
    data/document_chunks.pkl      - Python pickle

Pipeline position:
    prism-setup.sql -> prism-seed.py -> prism-chunks-import.py -> prism-indexes.sql

Usage:
    python prism-chunks-import.py [--format json|pkl] [--strict]

Options:
    --format     Force a specific input format. Default: auto-detect, prefer .pkl
                 when both are present (faster).
    --strict     Hard-fail on any chunk whose natural key cannot be resolved.
                 Default behavior is to warn and skip.

Requires:
    - python-oracledb
    - python-dotenv
    - prism-seed.py has been run against the target database
    - An export file produced by prism-chunks-export.py
    - Environment variables (see .env)
============================================================================
"""

import argparse
import array
import gzip
import json
import os
import pickle
import sys
import time

from dotenv import load_dotenv
load_dotenv()

import oracledb

oracledb.defaults.fetch_lobs = False


# ============================================================================
# Configuration
# ============================================================================

ORACLE_DSN = os.environ.get("DBCONNECTION")
ORACLE_USER = "prism"
ORACLE_PASSWORD = os.environ.get("DBPASSWORD")
ORACLE_WALLET_DIR = os.environ.get("ORACLE_WALLET_DIR")

EMBEDDING_MODEL = "DEMO_MODEL"

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data")
JSON_INPUT_FILE = os.path.join(DATA_DIR, "document_chunks.json.gz")
PKL_INPUT_FILE = os.path.join(DATA_DIR, "document_chunks.pkl")

BATCH_SIZE = 100


# ============================================================================
# Database Connection
# ============================================================================

def get_connection():
    """Create and return an Oracle database connection."""
    wallet_dir = ORACLE_WALLET_DIR.strip() if ORACLE_WALLET_DIR else ""
    if wallet_dir and os.path.isdir(wallet_dir):
        print(f"  Using wallet connection (wallet dir: {wallet_dir})")
        return oracledb.connect(
            user=ORACLE_USER,
            password=ORACLE_PASSWORD,
            dsn=ORACLE_DSN,
            config_dir=wallet_dir,
            wallet_location=wallet_dir,
            wallet_password=ORACLE_PASSWORD
        )
    else:
        print(f"  Using direct connection (DSN: {ORACLE_DSN})")
        return oracledb.connect(
            user=ORACLE_USER,
            password=ORACLE_PASSWORD,
            dsn=ORACLE_DSN
        )


# ============================================================================
# File Readers
# ============================================================================

def load_export(format_choice):
    """
    Load the export file. If format_choice is None, auto-detect.
    When both files are present, prefer .pkl (faster to deserialize).
    Returns the parsed payload: {"manifest": {...}, "chunks": [...]}.
    """
    pkl_exists = os.path.isfile(PKL_INPUT_FILE)
    json_exists = os.path.isfile(JSON_INPUT_FILE)

    if format_choice == "pkl":
        if not pkl_exists:
            raise FileNotFoundError(f"Pickle export not found: {PKL_INPUT_FILE}")
        path = PKL_INPUT_FILE
        use_pickle = True
    elif format_choice == "json":
        if not json_exists:
            raise FileNotFoundError(f"JSON export not found: {JSON_INPUT_FILE}")
        path = JSON_INPUT_FILE
        use_pickle = False
    else:
        # Auto-detect
        if pkl_exists:
            path = PKL_INPUT_FILE
            use_pickle = True
        elif json_exists:
            path = JSON_INPUT_FILE
            use_pickle = False
        else:
            raise FileNotFoundError(
                f"No export file found. Expected one of:\n"
                f"  {PKL_INPUT_FILE}\n"
                f"  {JSON_INPUT_FILE}\n"
                f"Run prism-chunks-export.py against a populated source database first."
            )

    print(f"Loading export from {path}...")
    if use_pickle:
        with open(path, "rb") as f:
            payload = pickle.load(f)
    else:
        with gzip.open(path, "rt", encoding="utf-8") as f:
            payload = json.load(f)

    size_mb = os.path.getsize(path) / (1024 * 1024)
    print(f"  Loaded {size_mb:.2f} MB.")
    return payload


# ============================================================================
# Target Database Validation
# ============================================================================

def validate_target(cursor, manifest):
    """
    Confirm the target database is compatible with the export:
    - DEMO_MODEL is loaded
    - Vector dimensions match
    - Source tables have been seeded
    - document_chunks is empty (or warn if not)
    Raises SystemExit on incompatibility.
    """
    print("\nValidating target database...")

    # 1. DEMO_MODEL loaded
    cursor.execute("""
        SELECT model_name FROM user_mining_models WHERE model_name = :m
    """, {"m": manifest["embedding_model_name"]})
    if not cursor.fetchone():
        print(f"  ERROR: Embedding model '{manifest['embedding_model_name']}' not loaded in target database.")
        print("  Load the ONNX model first (see prism-setup.sql Section 8).")
        sys.exit(1)
    print(f"  Model '{manifest['embedding_model_name']}' present.")

    # 2. Vector dimensions match
    cursor.execute("""
        SELECT VECTOR_EMBEDDING({model} USING 'test' AS data) FROM dual
    """.format(model=manifest["embedding_model_name"]))
    test_vec = cursor.fetchone()[0]
    target_dims = len(list(test_vec))
    if target_dims != manifest["vector_dimensions"]:
        print(f"  ERROR: Vector dimension mismatch.")
        print(f"    Export was made with {manifest['vector_dimensions']}-dim vectors.")
        print(f"    Target database produces {target_dims}-dim vectors.")
        print("  These are not compatible. Use the same ONNX model in both databases.")
        sys.exit(1)
    print(f"  Vector dimensions match ({target_dims}).")

    # 3. Source tables seeded
    for table in ("maintenance_logs", "inspection_reports", "inspection_findings"):
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        count = cursor.fetchone()[0]
        if count == 0:
            print(f"  ERROR: Source table '{table}' is empty.")
            print("  Run prism-seed.py before importing chunks.")
            sys.exit(1)
        print(f"  {table}: {count} rows.")

    # 4. document_chunks empty (warn if not, since we're about to add to it)
    cursor.execute("SELECT COUNT(*) FROM document_chunks")
    existing = cursor.fetchone()[0]
    if existing > 0:
        print(f"  WARNING: document_chunks already contains {existing} rows.")
        print("  This import will ADD to the existing data, which may create duplicates.")
        print("  Consider truncating document_chunks before continuing (Ctrl-C to abort).")
        time.sleep(3)


# ============================================================================
# Natural-Key Resolution
# ============================================================================

def build_lookup_maps(cursor):
    """
    Build lookup dicts that translate the natural keys in the export to
    the source_id values in the target database.

    Returns three dicts:
      - log_map:     {(asset_name, narrative): log_id}
      - report_map:  {(asset_name, inspector, summary): report_id}
      - finding_map: {(asset_name, inspector, report_summary, description): finding_id}
    """
    print("\nBuilding natural-key lookup maps from target database...")

    # Maintenance logs
    cursor.execute("""
        SELECT a.name, ml.narrative, ml.log_id
        FROM maintenance_logs ml
        JOIN infrastructure_assets a ON ml.asset_id = a.asset_id
    """)
    log_map = {(row[0], row[1]): row[2] for row in cursor}
    print(f"  Indexed {len(log_map)} maintenance logs.")

    # Inspection reports
    cursor.execute("""
        SELECT a.name, ir.inspector, ir.summary, ir.report_id
        FROM inspection_reports ir
        JOIN infrastructure_assets a ON ir.asset_id = a.asset_id
    """)
    report_map = {(row[0], row[1], row[2]): row[3] for row in cursor}
    print(f"  Indexed {len(report_map)} inspection reports.")

    # Inspection findings (joined back through report -> asset)
    cursor.execute("""
        SELECT a.name, ir.inspector, ir.summary, ifn.description, ifn.finding_id
        FROM inspection_findings ifn
        JOIN inspection_reports ir ON ifn.report_id = ir.report_id
        JOIN infrastructure_assets a ON ir.asset_id = a.asset_id
    """)
    finding_map = {(row[0], row[1], row[2], row[3]): row[4] for row in cursor}
    print(f"  Indexed {len(finding_map)} inspection findings.")

    return log_map, report_map, finding_map


def resolve_source_id(chunk, log_map, report_map, finding_map):
    """
    Look up the new source_id for a chunk based on its natural key.
    Returns the source_id, or None if not found.
    """
    source_table = chunk["source_table"]
    nk = chunk["natural_key"]

    if source_table == "maintenance_logs":
        return log_map.get((nk.get("asset_name"), nk.get("narrative")))
    elif source_table == "inspection_reports":
        return report_map.get((
            nk.get("asset_name"),
            nk.get("inspector"),
            nk.get("summary"),
        ))
    elif source_table == "inspection_findings":
        return finding_map.get((
            nk.get("asset_name"),
            nk.get("inspector"),
            nk.get("report_summary"),
            nk.get("finding_description"),
        ))
    else:
        return None


# ============================================================================
# Bulk Insert
# ============================================================================

INSERT_SQL = """
    INSERT INTO document_chunks
        (source_table, source_id, chunk_seq, chunk_text, embedding)
    VALUES
        (:source_table, :source_id, :chunk_seq, :chunk_text, :embedding)
"""


def import_chunks(conn, cursor, chunks, log_map, report_map, finding_map, strict):
    """
    Resolve natural keys to source_ids and INSERT each chunk.
    Returns counts: (inserted, skipped).
    """
    print("\nImporting chunks...")

    inserted = 0
    skipped = 0
    batch = []

    for chunk in chunks:
        source_id = resolve_source_id(chunk, log_map, report_map, finding_map)

        if source_id is None:
            nk_summary = ", ".join(f"{k}={v!r:.40}" for k, v in chunk["natural_key"].items() if v)
            msg = (f"Could not resolve natural key for {chunk['source_table']} chunk "
                   f"(seq={chunk['chunk_seq']}): {nk_summary}")
            if strict:
                print(f"  ERROR: {msg}")
                print("  Aborting due to --strict.")
                sys.exit(1)
            else:
                print(f"  WARNING: {msg}")
                skipped += 1
                continue

        # Embedding must be passed as array.array('f', ...) for VECTOR columns
        embedding = chunk["embedding"]
        if not isinstance(embedding, array.array):
            embedding = array.array("f", embedding)

        batch.append({
            "source_table": chunk["source_table"],
            "source_id": source_id,
            "chunk_seq": chunk["chunk_seq"],
            "chunk_text": chunk["chunk_text"],
            "embedding": embedding,
        })

        if len(batch) >= BATCH_SIZE:
            cursor.executemany(INSERT_SQL, batch)
            inserted += len(batch)
            conn.commit()
            print(f"  Inserted {inserted} chunks so far...")
            batch = []

    # Flush remaining
    if batch:
        cursor.executemany(INSERT_SQL, batch)
        inserted += len(batch)
        conn.commit()

    return inserted, skipped


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Import a Prism document_chunks export into a freshly-seeded database."
    )
    parser.add_argument(
        "--format",
        choices=["json", "pkl"],
        default=None,
        help="Force a specific input format. Default: auto-detect (prefer .pkl).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Hard-fail on any chunk whose natural key cannot be resolved.",
    )
    args = parser.parse_args()

    print("=" * 72)
    print("  PRISM: Document Chunks Importer")
    print("=" * 72)
    print()

    # Validate config
    missing = []
    if not ORACLE_DSN:
        missing.append("DBCONNECTION")
    if not ORACLE_PASSWORD:
        missing.append("DBPASSWORD")
    if missing:
        print(f"ERROR: Missing required environment variables: {', '.join(missing)}")
        sys.exit(1)

    # Load the export file
    try:
        payload = load_export(args.format)
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    manifest = payload["manifest"]
    chunks = payload["chunks"]

    print("\nExport manifest:")
    for key, value in manifest.items():
        print(f"  {key}: {value}")

    # Connect to target
    print("\nConnecting to target database...")
    conn = get_connection()
    cursor = conn.cursor()
    print("  Connected.")

    # Validate target compatibility
    validate_target(cursor, manifest)

    # Build lookup maps for natural-key resolution
    log_map, report_map, finding_map = build_lookup_maps(cursor)

    # Import
    start_time = time.time()
    inserted, skipped = import_chunks(
        conn, cursor, chunks, log_map, report_map, finding_map, args.strict
    )
    elapsed = time.time() - start_time

    # Summary
    print("\n--- Import Summary ---")
    cursor.execute("""
        SELECT source_table, COUNT(*) FROM document_chunks
        GROUP BY source_table ORDER BY source_table
    """)
    for row in cursor:
        print(f"  {row[0]:30s} {row[1]:>6d} chunks")

    cursor.execute("SELECT COUNT(*) FROM document_chunks")
    total = cursor.fetchone()[0]
    print(f"  {'TOTAL':30s} {total:>6d} chunks")
    print(f"\n  Inserted: {inserted}")
    print(f"  Skipped:  {skipped}")
    print(f"  Elapsed:  {elapsed:.1f} seconds")

    cursor.close()
    conn.close()

    print()
    print("=" * 72)
    print("  Chunk import complete.")
    print("  Next step: Run prism-indexes.sql to create the HNSW vector index.")
    print("=" * 72)


if __name__ == "__main__":
    main()
